# ============================================================
# ???????? ??????? ??????????? ? ??? ????????? INFO ? ????
# ============================================================
rootLogger.level=INFO
rootLogger.appenderRefs=stdout, file, fileAll
rootLogger.appenderRef.stdout.ref=STDOUT
rootLogger.appenderRef.file.ref=FILE
rootLogger.appenderRef.fileAll.ref=FILE_ALL

# ============================================================
# Appender: ????? ? ??????? (STDOUT)
# ============================================================
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss.SSS} %-5level [%t] %c{1}:%L - %msg%n

# ============================================================
# Appender: RollingFile ??? ?????? (WARN ? ????) ? ????? ? ./logs/errors_logs.log
# ============================================================
appender.file.type=RollingFile
appender.file.name=FILE
appender.file.fileName=./logs/errors_logs.log
appender.file.filePattern=./logs/errors_logs-%d{yyyy-MM-dd}.log.gz
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%t] %c{1}:%L - %msg%n
appender.file.append=true
appender.file.filter.threshold.type=ThresholdFilter
appender.file.filter.threshold.level=WARN
appender.file.policies.type=Policies
appender.file.policies.time.type=TimeBasedTriggeringPolicy
appender.file.policies.time.interval=1
appender.file.policies.time.modulate=true

# ============================================================
# Appender: RollingFile ??? ???? ??????? ? ????? ? ./logs/app.log
# ============================================================
appender.fileAll.type=RollingFile
appender.fileAll.name=FILE_ALL
appender.fileAll.fileName=./logs/app.log
appender.fileAll.filePattern=app/logs/app-%d{yyyy-MM-dd}.log.gz
appender.fileAll.layout.type=PatternLayout
appender.fileAll.layout.pattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%t] %c{1}:%L - %msg%n
appender.fileAll.append=true
appender.fileAll.policies.type=Policies
appender.fileAll.policies.time.type=TimeBasedTriggeringPolicy
appender.fileAll.policies.time.interval=1
appender.fileAll.policies.time.modulate=true

# ============================================================
# ?????? ??????????? ??? ????????? (????????? ???)
# ============================================================
logger.hibernate.name=org.hibernate
logger.hibernate.level=WARN

logger.spring.name=org.springframework
logger.spring.level=WARN

logger.rabbit.name=org.springframework.amqp
logger.rabbit.level=WARN

logger.netty.name=io.netty
logger.netty.level=WARN